import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/components/lib/utils";
import { ThemeProvider } from "@/components/ui/theme-provider";
import { UserAtomProvider } from "@/lib/context/UserContext";
import { ModAtomProvider } from "@/lib/context/ModContext";
import { RecoilProvider } from "@/lib/context/RecoilProvider";
import { Toaster } from "@/components/ui/sonner";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={cn(
					"min-h-screen bg-background font-sans antialiased",
					inter.className,
				)}
			>
				<ThemeProvider
					attribute="class"
					defaultTheme="system"
					enableSystem
					disableTransitionOnChange
				>
					<RecoilProvider>
						<UserAtomProvider>
							<ModAtomProvider>
								{children}
								<Toaster />
							</ModAtomProvider>
						</UserAtomProvider>
					</RecoilProvider>
				</ThemeProvider>
			</body>
		</html>
	);
}
